---
namespace: rancherfederal
name: rke2_ansible
version: 2.0.0
readme: README.md
authors:
  - Rancher Government <carbide@ranchergovernment.com>
description: Collection for rancherfederal/rke2-ansible

license_file: 'LICENSE'

tags: [infrastructure, linux, kubernetes, rancher, rke2]

repository: https://github.com/rancherfederal/rke2-ansible
documentation: https://github.com/rancherfederal/rke2-ansible
homepage: https://github.com/rancherfederal/rke2-ansible
issues: https://github.com/rancherfederal/rke2-ansible/issues

build_ignore:
  - tarball_install/*
  - testing
  - .github
