---

- hosts: rke2_servers
  become: yes
  roles:
    - role: rke2_server
  serial: 3

- hosts: rke2_agents
  become: yes
  roles:
    - role: rke2_agent
  serial: 3

- hosts: rke2_uninstall
  become: yes
  roles:
    - role: rke2_uninstall
  serial: 1
