---

- name: Create the /etc/rancher/rke2 config dir
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    recurse: true

- name: Run CIS-Hardening Tasks
  ansible.builtin.include_tasks: cis_hardening.yml

- name: Include task file add-systemd-env.yml
  ansible.builtin.include_tasks: add_ansible_managed_config.yml
  vars:
    file_contents: "{{ lookup('file', rke2_systemd_env_config_file_path) }}"
    file_destination: "/etc/default/{{ service_name }}"
    file_description: "systemd env options"
    file_path: "{{ rke2_systemd_env_config_file_path }}"

- name: "Include task file add_ansible_managed_config.yml for {{ file_description }}"
  ansible.builtin.include_tasks: add_ansible_managed_config.yml
  vars:
    file_contents: "{{ lookup('file', rke2_registry_config_file_path) }}"
    file_destination: "/etc/rancher/rke2/registries.yaml"
    file_description: "registry configuration"
    file_path: "{{ rke2_registry_config_file_path }}"

- name: "Include task file add_ansible_managed_config.yml for {{ file_description }}"
  ansible.builtin.include_tasks: add_ansible_managed_config.yml
  vars:
    file_contents: "{{ lookup('file', rke2_audit_policy_config_file_path) }}"
    file_destination: "/etc/rancher/rke2/audit-policy.yaml"
    file_description: "audit policy configuration"
    file_path: "{{ rke2_audit_policy_config_file_path }}"
  when:
    - inventory_hostname in groups['rke2_servers']

- name: "Include task file add_ansible_managed_config.yml for {{ file_description }}"
  ansible.builtin.include_tasks: add_ansible_managed_config.yml
  vars:
    file_contents: "{{ lookup('file', rke2_pod_security_admission_config_file_path) }}"
    file_destination: "/etc/rancher/rke2/pod-security-admission-config.yaml"
    file_description: "pod security admission config"
    file_path: "{{ rke2_pod_security_admission_config_file_path }}"
  when:
    - inventory_hostname in groups['rke2_servers']
