# This is a very simply upgrade playbook.
# Please note that it is not intended to solve all possible scenarios,
# every cluster has its own needs and an upgrade procedure should be
# handled on a per cluster basis. This basic playbook will upgrade
# one server at a time, then one worker at a time (by default).
# A server_upgrade_serial or worker_upgrade_serial variable can be
# provided to change this value.
---
- name: Warn user
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display warning
      ansible.builtin.pause:
        prompt: |-
          This upgrade playbook is rather simple and does not drain worker nodes before upgrading.
          This should work fine for simpler deployments, but this playbook should be used with
          caution. Do you wish to continue?
          (Press 'C' to continue the play or 'A' to Abort)

- name: Upgrade RKE2 servers
  hosts: rke2_servers
  any_errors_fatal: true
  become: true
  serial: "{{ server_upgrade_serial | default('1') }}"
  roles:
    - role: rke2

- name: Upgrade RKE2 agents
  hosts: rke2_agents
  any_errors_fatal: true
  become: true
  serial: "{{ worker_upgrade_serial | default('1') }}"
  roles:
    - role: rke2
