---
name: Lint

on:
  push:

jobs:

  ansible-lint:
    name: Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install ansible-lint
        run: pip3 install ansible-lint ansible

      - name: Version check
        run: |
          ansible --version
          ansible-lint --version

      - name: Run ansible-lint
        run: ansible-lint

  yaml-lint:
    name: YAML
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip3 install yamllint

      - name: Version check
        run: |
          yamllint --version

      - name: Run yamllint
        run: yamllint .

  vale-lint:
    name: Vale
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Install vale
        run: sudo snap install vale

      - name: Version check
        run: |
          vale --version

      - name: Run yamllint
        run: vale --glob='*.md' ./docs ./README.md