---
name: Rocky

on:
  pull_request:
  workflow_dispatch:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:

  "_8_":
    uses: ./.github/workflows/reusable_integration_testing.yml
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    with: 
      os: rocky8
      ssh_user: rocky
    secrets: inherit
  "_9_":
    uses: ./.github/workflows/reusable_integration_testing.yml
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    with: 
      os: rocky9
      ssh_user: rocky
    secrets: inherit