---
name: Rocky

on:
  pull_request:
  workflow_dispatch:

jobs:

  "_8_":
    uses: ./.github/workflows/reusable_integration_testing.yml
    with: 
      os: rocky8
      ssh_user: rocky
    secrets: inherit

  "_9_":
    uses: ./.github/workflows/reusable_integration_testing.yml
    with: 
      os: rocky9
      ssh_user: rocky
    secrets: inherit